/**
 * Textos del panel de administración (ES/EN).
 *
 * Viven aparte del diccionario público porque el panel tiene su propio
 * vocabulario (estados, métricas, acciones) que no debe mezclarse con el
 * copy del sitio.
 */
import type { Locale } from "@/types";

const es = {
  dashboard: "Panel",
  bookings: "Reservas",
  bookingDetail: "Reserva",
  tours: "Tours",
  transfers: "Traslados",
  testimonials: "Opiniones",
  gallery: "Galería",
  messages: "Mensajes",
  settings: "Ajustes",
  users: "Usuarios",
  totalRevenue: "Ingresos totales",
  monthRevenue: "Ingresos del mes",
  vsLastMonth: "vs. mes anterior",
  pendingBookings: "Pendientes",
  confirmedBookings: "Confirmadas",
  completedBookings: "Completadas",
  cancelledBookings: "Canceladas",
  totalGuests: "Viajeros",
  unreadMessages: "Mensajes sin leer",
  publishedTours: "Tours publicados",
  revenueByMonth: "Ingresos por mes",
  revenueByTour: "Ingresos por tour",
  recentBookings: "Reservas recientes",
  viewAll: "Ver todas",
  noData: "Sin datos todavía.",
  onlyConfirmedNote: "Solo cuentan confirmadas y completadas.",
  status: "Estado",
  payment: "Pago",
  customer: "Cliente",
  experience: "Experiencia",
  date: "Fecha",
  total: "Total",
  created: "Creada",
  actions: "Acciones",
  search: "Buscar por referencia, nombre o email…",
  allStatuses: "Todos los estados",
  filter: "Filtrar",
  dateFrom: "Desde",
  dateTo: "Hasta",
  pickDate: "Elige fecha",
  today: "Hoy",
  clear: "Borrar",
  prevMonth: "Mes anterior",
  nextMonth: "Mes siguiente",
  save: "Guardar cambios",
  saving: "Guardando…",
  saved: "Guardado.",
  back: "Volver",
  reference: "Referencia",
  guests: "Personas",
  phone: "Teléfono",
  email: "Email",
  country: "País",
  hotel: "Hotel",
  cruisePort: "Terminal de cruceros",
  notes: "Notas",
  history: "Historial",
  markConfirmed: "Confirmar",
  markCompleted: "Completar",
  markCancelled: "Cancelar",
  markPaid: "Marcar pagada",
  markPartial: "Pago parcial",
  confirmTitle: "Confirmar reserva",
  statusPending: "Pendiente",
  statusConfirmed: "Confirmada",
  statusCompleted: "Completada",
  statusCancelled: "Cancelada",
  payUnpaid: "Sin pagar",
  payPartial: "Parcial",
  payPaid: "Pagada",
  payRefunded: "Reembolsada",
};

const en: typeof es = {
  dashboard: "Dashboard",
  bookings: "Bookings",
  bookingDetail: "Booking",
  tours: "Tours",
  transfers: "Transfers",
  testimonials: "Reviews",
  gallery: "Gallery",
  messages: "Messages",
  settings: "Settings",
  users: "Users",
  totalRevenue: "Total revenue",
  monthRevenue: "This month",
  vsLastMonth: "vs. last month",
  pendingBookings: "Pending",
  confirmedBookings: "Confirmed",
  completedBookings: "Completed",
  cancelledBookings: "Cancelled",
  totalGuests: "Travellers",
  unreadMessages: "Unread messages",
  publishedTours: "Published tours",
  revenueByMonth: "Revenue by month",
  revenueByTour: "Revenue by tour",
  recentBookings: "Recent bookings",
  viewAll: "View all",
  noData: "No data yet.",
  onlyConfirmedNote: "Only confirmed and completed count.",
  status: "Status",
  payment: "Payment",
  customer: "Customer",
  experience: "Experience",
  date: "Date",
  total: "Total",
  created: "Created",
  actions: "Actions",
  search: "Search by reference, name or email…",
  allStatuses: "All statuses",
  filter: "Filter",
  dateFrom: "From",
  dateTo: "To",
  pickDate: "Pick a date",
  today: "Today",
  clear: "Clear",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  save: "Save changes",
  saving: "Saving…",
  saved: "Saved.",
  back: "Back",
  reference: "Reference",
  guests: "Guests",
  phone: "Phone",
  email: "Email",
  country: "Country",
  hotel: "Hotel",
  cruisePort: "Cruise terminal",
  notes: "Notes",
  history: "History",
  markConfirmed: "Confirm",
  markCompleted: "Complete",
  markCancelled: "Cancel",
  markPaid: "Mark paid",
  markPartial: "Partial payment",
  confirmTitle: "Confirm booking",
  statusPending: "Pending",
  statusConfirmed: "Confirmed",
  statusCompleted: "Completed",
  statusCancelled: "Cancelled",
  payUnpaid: "Unpaid",
  payPartial: "Partial",
  payPaid: "Paid",
  payRefunded: "Refunded",
};

export function adminTexts(locale: Locale): typeof es {
  return locale === "es" ? es : en;
}
